### ISSUE TITLE
Response from Alexa

### ISSUE THREAD

**Issue by genialkartik** [AmazonAlexaDeveloperCommunityLPU/Antariksh-Facts#1]
How does Alexa reply our queries. Does it searches our queries on internet or the developer that have build that skill embeds the answers already. Like in Food facts skill example when we ask "Alexa, tell me a fun fact" so does it searches about the fact randomly from internet or does the developer who created that skill set have already embedded some facts already?

**Comment by Razdeep** [comment]
Since this skill is intended as a guide for beginners, it picks a random fact from several embedded facts and sends it as a response.

**Comment by genialkartik** [comment]
Got it. Thank you for response @Razdeep .

**Comment by Razdeep** [comment]
Anytime :) 
Closing this issue
